apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
      - name: lb-container
        image: ip-rotator-tool
        ports:
        - containerPort: 8080
