apiVersion: v1
kind: Service
metadata:
  name: dened-service
  labels:
    app: dened
spec:
  type: ClusterIP
  selector:
    app: dened
  ports:
    - name: http
      port: 8080
      targetPort: 8080
